disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - todo
  - trailing_newline
  - type_name
  - function_body_length
  - missing_docs
  - valid_docs
  - cyclomatic_complexity
  - type_body_length
  - function_parameter_count
  - file_length
  - mark
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - redundant_string_enum_value
  - large_tuple
  - class_delegate_protocol
  - syntactic_sugar
  - implicit_getter
  - weak_delegate
  - shorthand_operator
  - trailing_comma
  - unused_optional_binding
  - private_over_fileprivate
  - empty_enum_arguments
  - discarded_notification_center_observer
  - block_based_kvo
  - nesting
  - is_disjoint
  - multiple_closures_with_trailing_closure
  - fallthrough
  - switch_case_alignment
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - legacy_cggeometry_functions
  - unneeded_break_in_switch
  - closure_parameter_position

# The following rules are disabled for now because firefox code breaks them. Try to reintroduce them gradually
  - force_try
  - force_cast
  - unused_setter_value
  - void_return
  - reduce_boolean
  - notification_center_detachment


opt_in_rules: # some rules are only opt-in
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  - explicit_init
  - shorthand_operator
  - deployment_target
  - duplicate_imports
  - empty_string
  - empty_count
  - overridden_super_call
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_objc_attribute
  - unused_import

  # The following rules are disabled for now because firefox code breaks them. Try to reintroduce them gradually
  # - discouraged_optional_collection
  # - redundant_type_annotation
  # - file_header
  
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - ThirdParty
  - FxA
  - FxAClient
  - build
  - UITests/EarlGrey.swift
  - Storage/ThirdParty/SwiftData.swift
  - UITests/
  - XCUITests/
  - SyncTests/
  - StorageTests/
  - ReadingListTests/
  - ClientTests/
  - AccountTests/
  - fastlane/
  - SharedTests/
  - Client/Assets/Search/get_supported_locales.swift
  - Storage/SQL/SQLiteHistory.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
trailing_semicolon: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_try: warning
force_cast: warning

# The following rule is useless, but is kept for compatibility with firefox code for now. 
# Try to reduce to 140 gradually.
line_length: 1000

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
