variables:
- group: AccessTokens

trigger:
- master
- develop

strategy:
  matrix:
    Cliqz:
      scheme: 'Cliqz'
      actions: 'clean test build'
pool:
  vmImage: 'macOS 10.14'

steps:
- bash: |
    sudo xcode-select --switch /Applications/Xcode_10.3.app
  displayName: 'Change XCode to 10.3'

- task: NodeTool@0
  displayName: 'Define Node to v9.11.2'
  inputs:
    versionSpec: '9.11.2'

- bash: |
    set -x
    npm i -g npm@6.5
    /usr/local/bin/npm ci
  displayName: 'Install Node modules'

- bash: |
    set -x
    npm run build
  displayName: Generate User Scripts

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.6'
    addToPath: true
    
- bash: |
    set -x
    gem install bundler:2.0.2
    bundle install --retry=3
    bundle exec pod install
  displayName: 'Install CocoaPods'

- bash: |
    carthage version
    carthage bootstrap --platform iOS --no-use-ssh
  env:
    GITHUB_ACCESS_TOKEN: $(CLIQZ_CI_GITHUB_ACCESS_TOKEN)
  displayName: 'Install Carthage'

- bash: bundle exec fastlane lint
  displayName: 'Lint'

- task: Xcode@5
  inputs:
    actions: '$(actions)'
    sdk: 'iphonesimulator'
    xcWorkspacePath: 'UserAgent.xcworkspace'
    scheme: '$(scheme)'
    packageApp: true
    exportPath: 'output/$(SDK)/$(scheme)'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 8'
    publishJUnitResults: true
