# Prepare, Build and Archive Cliqz-Browser-ios

variables:
- group: AccessTokens

trigger:
- master

strategy:
  matrix:
    Cliqz:
      scheme: 'Fennec'
      actions: 'clean build'
pool:
  vmImage: 'macOS 10.14'

steps:
- bash: |
    sudo xcode-select --switch /Applications/Xcode_10.3.app
  displayName: 'Change XCode to 10.3'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.6'
    addToPath: true
    
- script: |
    CALL gem install bundler
    bundle install --retry=3
    bundle exec pod install
  displayName: 'Install CocoaPods'

- bash: carthage bootstrap --platform iOS
  env:
    GITHUB_ACCESS_TOKEN: $(CLIQZ_CI_GITHUB_ACCESS_TOKEN)

- task: NodeTool@0
  displayName: 'Define Node to v9.11.2'
  inputs:
    versionSpec: '9.11.2'

- bash: |
    set -x
    npm i -g npm@6.5
    /usr/local/bin/npm ci
  displayName: 'Install Node modules'

- script: xcodebuild -workspace Client.xcworkspace -scheme $(scheme) -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.1,name=iPhone 6s" OTHER_SWIFT_FLAGS='$(value) -DAUTOMATION' ONLY_ACTIVE_ARCH=NO -derivedDataPath $(actions)
  displayName: 'Xcode Build for Simulator'

# - task: ArchiveFiles@2
#   displayName: 'Archive Build'
#   inputs:
#     rootFolderOrFile: 'clean/Build/Products/$(scheme)-iphonesimulator/Client.app'
#     archiveType: 'zip'
#     tarCompression: 'none'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(scheme).zip'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Build'
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: $(scheme)
